### ISSUE TITLE
Nice to have website customizations

### ISSUE THREAD

**Issue by hfend** [dz-experts/projects.covid19dz.com#2]
Some nice to have styling and layout customizations

- [ ] Change the "academic hat" icon in the header and favicon with something more suitable.
- [ ] Show the arabic page with RTL styling.
- [ ] Hide currently non-needed "next" and "previous" page links from the footer.
- [ ] Show an Algerian flag icon somewhere in the header or footer, so people can relate more with the website.

**Comment by HouariZegai** [comment]
Ping @MiloudiMohamed
